const initialData = [
    {
      no: 1,
      taskName: "Task 1",
      assignedTo: "Ram",
      startDate: "2024-01-01",
      endDate: "2024-01-09",
      tags: ["Tag", "Tag"],
      followers: "Follower 1, Follower 2",
      descriptions: "Description for Task 1",
    },
    {
      no: 2,
      taskName: "Task 2",
      assignedTo: "Jhon",
      startDate: "2024-01-05",
      endDate: "2024-01-15",
      tags: ["Tag"],
      followers: "Follower 3, Follower 4",
      descriptions: "Description for Task 2",
    },
    {
      no: 3,
      taskName: "Task 3",
      assignedTo: "Jason",
      startDate: "2024-01-05",
      endDate: "2024-01-15",
      tags: ["Tag", "Tag"],
      followers: "Follower 3, Follower 4",
      descriptions: "Description for Task 3",
    },
    {
      no: 4,
      taskName: "Task 4",
      assignedTo: "Sunny",
      startDate: "2024-01-05",
      endDate: "2024-01-15",
      tags: ["Tag5"],
      followers: "Follower 3, Follower 4",
      descriptions: "Description for Task 4",
    },
    {
      no: 5,
      taskName: "Task 5",
      assignedTo: "Marik",
      startDate: "2024-01-05",
      endDate: "2024-01-15",
      tags: ["Tag", "Tag"],
      followers: "Follower 2",
      descriptions: "Description for Task 5",
    },
  ];
  
  export default initialData;
  